name: Waka Readme

on:
  schedule:
    # Запуск каждые 12 часов
    - cron: '0 */12 * * *'
  workflow_dispatch: # Возможность запустить вручную

jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_TITLE: true
          SECTION_NAME: waka
          BLOCKS: ░▒▓█ # Стиль бара как на скрине
          TIME_RANGE: last_7_days # Можно поставить all_time для статистики за год
          SHOW_TIME_DIFFERENCE: true
          SHOW_TOTAL_TIME: true
          SHOW_MASKED_TIME: true
          LANG_COUNT: 10
          SHOW_PROJECTS: false # Если хочешь только языки
