name: Waka Readme

on:
  schedule:
    # Обновление каждые 12 часов
    - cron: "0 */12 * * *"
  workflow_dispatch: # Чтобы можно было запустить кнопкой

jobs:
  update-readme:
    name: WakaReadme DevMetrics
    runs-on: ubuntu-latest
    steps:
      # Важный шаг: чекаут репозитория, чтобы бот мог в него писать
      - uses: actions/checkout@v3

      - uses: athul/waka-readme@master
        with:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          ### Настройки контента
          SHOW_TITLE: true
          SECTION_NAME: waka
          # Вот эти блоки сделают график как на скрине (от темного к светлому)
          BLOCKS: ⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣷⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀
          TIME_RANGE: all_time # Или last_year, чтобы собрать побольше статы
          LANG_COUNT: 10
          SHOW_TIME: true
          SHOW_TOTAL: true
          SHOW_MASKED_TIME: false
          STOP_AT_OTHER: true
          ### Настройки коммита
          COMMIT_MESSAGE: "Updated waka-readme graph with new metrics"
          TARGET_BRANCH: main  # ПРОВЕРЬ: если у тебя ветка называется master, замени на master
          COMMITTER_NAME: GitHubActionBot
          COMMITTER_EMAIL: action-bot@github.com
